---
name: lein_test

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  run-lein-tests:
    name: lein test - Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - '21'
          - '17'
          - '11'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@13.2
        with:
          cli: latest              # Clojure CLI based on tools.deps
          lein: latest                  # Leiningen
          boot: latest                  # Boot.clj
          bb: latest                    # Babashka
          clj-kondo: latest        # Clj-kondo
          cljstyle: latest             # cljstyle
          zprint: latest                # zprint
      - name: Run lein tests with update profile
        run: |
          set -x
          set -e
          lein version
          echo "Running tests"
          lein -U test

  tests:
    needs:
      - run-lein-tests
    runs-on: ubuntu-24.04
    name: Test suite
    steps:
      - run: echo Test suite completed
